export const COMPANY_OPTIONS = [
  { value: "all", label: "전체 회사 비교" },
  { value: "Oriental Motor", label: "Oriental Motor" },
  { value: "THK", label: "THK" },
  { value: "Hyosung", label: "효성" },
  { value: "Nanomotion", label: "Nanomotion" },
  { value: "Nanotec", label: "Nanotec" },
  { value: "Yaskawa", label: "Yaskawa" },
  { value: "Mitsubishi Electric", label: "Mitsubishi Electric" },
  { value: "ABB", label: "ABB" },
  { value: "Siemens", label: "Siemens" },
  { value: "SEW-EURODRIVE", label: "SEW-EURODRIVE" },
  { value: "Kollmorgen", label: "Kollmorgen" },
  { value: "MISUMI", label: "MISUMI" },
];

export const WEB_SEARCH_PROVIDERS = [
  {
    company: "Oriental Motor",
    domains: ["catalog.orientalmotor.com", "orientalmotor.com"],
    keyword: "Oriental Motor motor",
  },
  {
    company: "THK",
    domains: ["thk.com"],
    keyword: "THK electric actuator KR SKR linear",
  },
  {
    company: "Hyosung",
    domains: ["hyosungheavyindustries.com"],
    keyword: "Hyosung low voltage motor",
  },
  {
    company: "Nanomotion",
    domains: ["nanomotion.com"],
    keyword: "Nanomotion motor",
  },
  {
    company: "Nanotec",
    domains: ["nanotec.com"],
    keyword: "Nanotec motor stepper bldc linear actuator",
  },
  {
    company: "Yaskawa",
    domains: ["yaskawa.com"],
    keyword: "Yaskawa motor servo",
  },
  {
    company: "Mitsubishi Electric",
    domains: ["mitsubishielectric.com", "mitsubishielectric-fa.com"],
    keyword: "Mitsubishi Electric servo motor",
  },
  {
    company: "ABB",
    domains: ["abb.com"],
    keyword: "ABB motor servo",
  },
  {
    company: "Siemens",
    domains: ["siemens.com"],
    keyword: "Siemens motor servo",
  },
  {
    company: "SEW-EURODRIVE",
    domains: ["sew-eurodrive.com"],
    keyword: "SEW EURODRIVE motor gearmotor",
  },
  {
    company: "Kollmorgen",
    domains: ["kollmorgen.com"],
    keyword: "Kollmorgen motor servo",
  },
  {
    company: "MISUMI",
    domains: ["misumi-ec.com"],
    keyword: "MISUMI stepping motor LM guide ball screw linear actuator",
  },
];

export const COMPANY_SITE_LINKS = [
  {
    id: "site-oriental-motor",
    company: "Oriental Motor",
    type: "공식 사이트",
    title: "Oriental Motor 공식 제품 사이트",
    description: "브러시리스, 스텝, 서보, 감속기 제품 검색용",
    href: "https://www.orientalmotor.com/",
  },
  {
    id: "site-thk",
    company: "THK",
    type: "공식 사이트",
    title: "THK 공식 제품 사이트",
    description: "KR·SKR·GLM 일체형 전동 액추에이터, LM가이드, 볼스크류 검색용",
    href: "https://www.thk.com/jp/en/products/categories/electric_actuator.html",
  },
  {
    id: "site-hyosung",
    company: "Hyosung",
    type: "공식 사이트",
    title: "효성중공업 전동기 사이트",
    description: "저압 모터, 산업용 전동기 정보 검색용",
    href: "https://www.hyosungheavyindustries.com/kr/business/power-industrial-system/motor.do",
  },
  {
    id: "site-nanomotion",
    company: "Nanomotion",
    type: "공식 사이트",
    title: "Nanomotion 공식 사이트",
    description: "초정밀 직결 모터, 스테이지용 제품 검색용",
    href: "https://www.nanomotion.com/",
  },
  {
    id: "site-nanotec",
    company: "Nanotec",
    type: "공식 사이트",
    title: "Nanotec 공식 사이트",
    description: "스텝모터, BLDC, 리니어 액추에이터, 기어박스 검색용",
    href: "https://www.nanotec.com/us/en/products",
  },
  {
    id: "site-yaskawa",
    company: "Yaskawa",
    type: "공식 사이트",
    title: "Yaskawa 공식 사이트",
    description: "서보모터, 드라이브, 모션 제품 검색용",
    href: "https://www.yaskawa.com/",
  },
  {
    id: "site-mitsubishi-electric",
    company: "Mitsubishi Electric",
    type: "공식 사이트",
    title: "Mitsubishi Electric FA 공식 사이트",
    description: "서보 시스템, AC 모터 제품 검색용",
    href: "https://www.mitsubishielectric-fa.com/",
  },
  {
    id: "site-abb",
    company: "ABB",
    type: "공식 사이트",
    title: "ABB Motion 공식 사이트",
    description: "산업용 모터, 서보, 모션 제품 검색용",
    href: "https://new.abb.com/motors-generators",
  },
  {
    id: "site-siemens",
    company: "Siemens",
    type: "공식 사이트",
    title: "Siemens Motion Control 공식 사이트",
    description: "서보모터, 모션 제어, 산업 자동화 검색용",
    href: "https://www.siemens.com/",
  },
  {
    id: "site-sew-eurodrive",
    company: "SEW-EURODRIVE",
    type: "공식 사이트",
    title: "SEW-EURODRIVE 공식 사이트",
    description: "기어모터, 서보모터, 드라이브 시스템 검색용",
    href: "https://www.sew-eurodrive.com/",
  },
  {
    id: "site-kollmorgen",
    company: "Kollmorgen",
    type: "공식 사이트",
    title: "Kollmorgen 공식 사이트",
    description: "서보모터, 드라이브, AGV 모션 제품 검색용",
    href: "https://www.kollmorgen.com/",
  },
  {
    id: "site-misumi",
    company: "MISUMI",
    type: "공식 사이트",
    title: "MISUMI 공식 사이트 (misumi-ec.com)",
    description: "LM가이드, 볼스크류, 스텝모터, 전동 실린더 등 표준 기계부품 검색용",
    href: "https://kr.misumi-ec.com/",
  },
];
