const STANDARD_GEAR_RATIOS = [1, 3, 5, 7, 10, 15, 20, 30, 50];

export const SPEED_MODE_OPTIONS = [
  { value: "constant", label: "정속" },
  { value: "variable", label: "가변속" },
];

export const SCREW_TYPE_OPTIONS = [
  {
    value: "ball",
    label: "볼스크류",
    guide: "빠른 이송과 높은 효율이 필요한 장비에 많이 씁니다.",
  },
  {
    value: "lead",
    label: "일반 리드스크류",
    guide: "구조가 단순하고 저속 이송에 무난한 방식입니다.",
  },
  {
    value: "trapezoidal",
    label: "사다리꼴 나사",
    guide: "하중 유지와 수동 조정이 필요한 장비에 많이 씁니다.",
  },
];

export const SCREW_SPEC_OPTIONS = [
  { screwType: "ball", value: "M6", label: "M6", leadMm: 1, guide: "소형 정밀 이송용" },
  { screwType: "ball", value: "M8", label: "M8", leadMm: 2, guide: "소형 이송의 기본 크기" },
  { screwType: "ball", value: "M10", label: "M10", leadMm: 2, guide: "가벼운 하중용 기본 크기" },
  { screwType: "ball", value: "M12", label: "M12", leadMm: 4, guide: "보통 하중용 무난한 크기" },
  { screwType: "ball", value: "M16", label: "M16", leadMm: 5, guide: "중간 하중과 속도 균형형" },
  { screwType: "ball", value: "M20", label: "M20", leadMm: 10, guide: "중하중용 빠른 이송형" },
  { screwType: "ball", value: "M25", label: "M25", leadMm: 10, guide: "고하중용 큰 크기" },
  { screwType: "ball", value: "M30", label: "M30", leadMm: 12, guide: "고하중 이송용 대형 크기" },
  { screwType: "ball", value: "M36", label: "M36", leadMm: 16, guide: "매우 무거운 하중용" },
  { screwType: "ball", value: "M42", label: "M42", leadMm: 20, guide: "대형 설비용 초고하중용" },
  { screwType: "lead", value: "M3", label: "M3", leadMm: 0.5, guide: "초소형 정밀 장비용" },
  { screwType: "lead", value: "M4", label: "M4", leadMm: 0.7, guide: "아주 작은 이송 장치용" },
  { screwType: "lead", value: "M5", label: "M5", leadMm: 0.8, guide: "소형 경량 이송용" },
  { screwType: "lead", value: "M6", label: "M6", leadMm: 1, guide: "소형 장비 기본 크기" },
  { screwType: "lead", value: "M8", label: "M8", leadMm: 1.25, guide: "소형 하중 이송용" },
  { screwType: "lead", value: "M10", label: "M10", leadMm: 1.5, guide: "보통 하중의 기본 크기" },
  { screwType: "lead", value: "M12", label: "M12", leadMm: 1.75, guide: "조금 큰 하중용" },
  { screwType: "lead", value: "M16", label: "M16", leadMm: 2, guide: "중하중 저속 이송용" },
  { screwType: "lead", value: "M20", label: "M20", leadMm: 2.5, guide: "중하중 장비용" },
  { screwType: "lead", value: "M24", label: "M24", leadMm: 3, guide: "큰 하중을 천천히 움직일 때" },
  { screwType: "lead", value: "M30", label: "M30", leadMm: 3.5, guide: "대형 장비용" },
  { screwType: "lead", value: "M36", label: "M36", leadMm: 4, guide: "대형 하중 유지용" },
  { screwType: "trapezoidal", value: "M6", label: "M6", leadMm: 1, guide: "작은 테이블 리프트용" },
  { screwType: "trapezoidal", value: "M8", label: "M8", leadMm: 1.5, guide: "소형 하중 유지용" },
  { screwType: "trapezoidal", value: "M10", label: "M10", leadMm: 2, guide: "보통 장비의 기본 크기" },
  { screwType: "trapezoidal", value: "M12", label: "M12", leadMm: 3, guide: "중간 하중용" },
  { screwType: "trapezoidal", value: "M16", label: "M16", leadMm: 4, guide: "중하중 리프트용" },
  { screwType: "trapezoidal", value: "M20", label: "M20", leadMm: 4, guide: "하중 유지가 중요한 경우" },
  { screwType: "trapezoidal", value: "M24", label: "M24", leadMm: 5, guide: "대형 테이블 리프트용" },
  { screwType: "trapezoidal", value: "M30", label: "M30", leadMm: 6, guide: "고하중 특수 장비용" },
  { screwType: "trapezoidal", value: "M36", label: "M36", leadMm: 6, guide: "아주 큰 하중용" },
  { screwType: "custom", value: "CUSTOM", label: "직접 입력", leadMm: null, guide: "리드 값을 직접 입력합니다." },
];

export const MOTOR_TYPE_OPTIONS = [
  "전체",
  "브러시리스 모터",
  "클로즈드루프 스텝모터",
  "2상 스텝모터",
  "5상 스텝모터",
  "3상 유도전동기",
  "초소형 정밀 모터",
];

export const PHASE_OPTIONS = ["전체", "DC", "1상 AC", "2상", "3상 AC", "5상"];

export const COMPANY_MANUALS = [
  {
    id: "thk-kr-actuator",
    company: "THK",
    type: "제품 카탈로그",
    title: "THK KR Series 전동 액추에이터 카탈로그",
    description: "볼스크류·LM가이드 내장 일체형 액추에이터, 허용 하중·속도·스트로크 확인용",
    href: "https://www.thk.com/jp/en/products/categories/electric_actuator/kr.html",
  },
  {
    id: "thk-skr-actuator",
    company: "THK",
    type: "제품 카탈로그",
    title: "THK SKR Series 슬림형 액추에이터 카탈로그",
    description: "폭이 좁은 설계용 슬림 일체형 액추에이터, 소형·고속 이송 사양 확인용",
    href: "https://www.thk.com/jp/en/products/categories/electric_actuator/skr.html",
  },
  {
    id: "oriental-ble2",
    company: "Oriental Motor",
    type: "시리즈 자료",
    title: "BLE2 Series 제품 자료",
    description: "브러시리스 DC 속도제어 모터와 기어드 타입 확인용",
    href: "https://catalog.orientalmotor.com/viewitems/ble2-series-brushless-dc-motor-speed-control/120w-ble2-series-brushless-dc-motors",
  },
  {
    id: "oriental-blv",
    company: "Oriental Motor",
    type: "시리즈 자료",
    title: "BLV Series R Type 자료",
    description: "DC 입력 브레이크 타입과 기어드 조합 확인용",
    href: "https://www.orientalmotor.com/brushless-dc-motors-gear-motors/brushless-dc-motors-gear-motors-blv-r-type.html",
  },
  {
    id: "oriental-az",
    company: "Oriental Motor",
    type: "시리즈 자료",
    title: "AZ Series 자료",
    description: "클로즈드루프 스텝모터와 저백래시 기어드 타입 확인용",
    href: "https://www.orientalmotor.com/servo-motors/hybrid-servo-motor-stepper-motor-az-series.html",
  },
  {
    id: "nanomotion-rc3",
    company: "Nanomotion",
    type: "제품 매뉴얼",
    title: "RC3 Ultrasonic Motor 매뉴얼",
    description: "RC3 초음파 직결 모터, 최대 180 mm/s, 동적 추력 12 N 기준",
    href: "/manuals/nanomotion/nanomotion-rc3-ultrasonic-motor-user-manual.pdf",
  },
  {
    id: "nanomotion-edge",
    company: "Nanomotion",
    type: "제품 매뉴얼",
    title: "EDGE / EDGE-4X 매뉴얼",
    description: "초소형 정밀 모터, 최대 150~180 mm/s, 0.32~1.3 N 추력 기준",
    href: "/manuals/nanomotion/nanomotion-edge-edge-4x-motors-user-manual.pdf",
  },
  {
    id: "nanomotion-hr",
    company: "Nanomotion",
    type: "제품 매뉴얼",
    title: "HR Motors 매뉴얼",
    description: "HR1~HR8 직결 정밀 모터, 최대 250 mm/s, 4.5~36 N 추력 기준",
    href: "/manuals/nanomotion/nanomotion-hr-motors-user-manual.pdf",
  },
  {
    id: "hyosung-lv-motor",
    company: "Hyosung",
    type: "모터 매뉴얼",
    title: "효성 저압 모터 카탈로그",
    description: "저압 3상 유도전동기 출력, 프레임, 효율, 극수 확인용",
    href: "/manuals/hyosung/hyosung-low-voltage-motors-catalog-kr.pdf",
  },
  {
    id: "hyosung-mms",
    company: "Hyosung",
    type: "수배 전력기기",
    title: "모터보호용 배선용차단기 (MMS)",
    description: "모터 보호 차단기 검토용 매뉴얼",
    href: "/manuals/hyosung/hyosung-mms.pdf",
  },
  {
    id: "hyosung-empr",
    company: "Hyosung",
    type: "수배 전력기기",
    title: "전자식 모터보호 계전기 (EMPR)",
    description: "모터 보호 계전기 검토용 매뉴얼",
    href: "/manuals/hyosung/hyosung-empr.pdf",
  },
  {
    id: "hyosung-lvss",
    company: "Hyosung",
    type: "기동기기",
    title: "LVSS Soft Starter",
    description: "저압 모터 기동기 검토용 매뉴얼",
    href: "/manuals/hyosung/hyosung-lvss-soft-starter.pdf",
  },
  {
    id: "hyosung-motorsol",
    company: "Hyosung",
    type: "기동기기",
    title: "Motorsol Soft Starter",
    description: "소프트 스타터 기동 조건 검토용 매뉴얼",
    href: "/manuals/hyosung/hyosung-motorsol-soft-starter.pdf",
  },
];

const ORIENTAL_MOTOR_PRODUCTS = [
  {
    company: "Oriental Motor",
    series: "BLE2 Series",
    productName: "BLE2 30W Parallel Shaft Gearhead",
    modelNumber: "BLM230HP-GFV / GFV2G15S / BLE2D30-A",
    sampleModel: "BLE2 30W + Parallel Shaft Gearhead",
    motorType: "브러시리스 모터",
    phaseTypes: ["1상 AC", "3상 AC"],
    imageUrl: "https://catalog.orientalmotor.com/Asset/ble5120hp-_as-img.jpg",
    powerW: 30,
    maxMotorRpm: 4000,
    minMotorRpm: 80,
    gearheadType: "평행축 감속기",
    availableRatios: [5, 10, 15, 20, 30, 50],
    maxOutputTorqueNm: 6,
    verticalReady: true,
    notes: "경량 부하와 소형 장비용 기본형입니다. 전자브레이크 옵션도 검토할 수 있습니다.",
    sourceLabel: "BLE2 30W official spec",
    sourceUrl: "https://catalog.orientalmotor.com/viewitems/30w-brushless-dc-motor-speed-control-systems/30w-ble2-series-brushless-dc-motors",
  },
  {
    company: "Oriental Motor",
    series: "BLE2 Series",
    productName: "BLE2 120W Parallel Shaft Gearhead",
    modelNumber: "BLM5120HPK / 5H100S / BLE2D120-C",
    sampleModel: "BLE2 120W + Parallel Shaft Gearhead",
    motorType: "브러시리스 모터",
    phaseTypes: ["1상 AC", "3상 AC"],
    imageUrl: "https://catalog.orientalmotor.com/Asset/ble5120hpk-5h_c-img.jpg",
    powerW: 120,
    maxMotorRpm: 4000,
    minMotorRpm: 80,
    gearheadType: "평행축 감속기",
    availableRatios: [5, 10, 15, 20, 30, 50, 100, 200],
    maxOutputTorqueNm: 30,
    verticalReady: true,
    notes: "중소형 장비의 이송축에 많이 쓰는 표준형입니다. 브레이크 옵션도 선택 가능합니다.",
    sourceLabel: "BLE2 120W official spec",
    sourceUrl: "https://catalog.orientalmotor.com/viewitems/ble2-series-brushless-dc-motor-speed-control/120w-ble2-series-brushless-dc-motors",
  },
  {
    company: "Oriental Motor",
    series: "BLE2 Series",
    productName: "BLE2 200W Parallel Shaft Gearhead",
    modelNumber: "BLM5200HPK / 5AB10B / BLE2D200-C",
    sampleModel: "BLE2 200W + Parallel Shaft Gearhead",
    motorType: "브러시리스 모터",
    phaseTypes: ["1상 AC", "3상 AC"],
    imageUrl: "https://catalog.orientalmotor.com/Asset/ble5200hpk-5_b_a-l-img.jpg",
    powerW: 200,
    maxMotorRpm: 4000,
    minMotorRpm: 80,
    gearheadType: "평행축 감속기",
    availableRatios: [5, 10, 15, 20, 30, 50, 100, 200, 300, 450, 600, 1200],
    maxOutputTorqueNm: 198,
    verticalReady: true,
    notes: "중하중 이송용으로 넉넉한 감속기 조합을 고를 수 있습니다.",
    sourceLabel: "BLE2 200W official spec",
    sourceUrl: "https://catalog.orientalmotor.com/viewitems/ble2-series-brushless-dc-motor-speed-control/200w-ble2-series-brushless-dc-motors",
  },
  {
    company: "Oriental Motor",
    series: "BLV Series R Type",
    productName: "BLV R 100W Electromagnetic Brake",
    modelNumber: "BLMR5100KM-30-F",
    sampleModel: "BLV R 100W Brake Type",
    motorType: "브러시리스 모터",
    phaseTypes: ["DC"],
    imageUrl: "https://catalog.orientalmotor.com/Asset/BLMR5100KM-30-F-img.jpg",
    powerW: 100,
    maxMotorRpm: 4000,
    minMotorRpm: 80,
    gearheadType: "평행축 감속기",
    availableRatios: [10, 20, 30, 50, 100, 200],
    maxOutputTorqueNm: 27.4,
    verticalReady: true,
    notes: "배터리 구동이나 수직축 검토에 자주 쓰는 브레이크 일체형입니다.",
    sourceLabel: "BLV R official spec",
    sourceUrl: "https://www.orientalmotor.com/brushless-dc-motors-gear-motors/brushless-dc-motors-gear-motors-blv-r-type.html",
  },
  {
    company: "Oriental Motor",
    series: "AZ Series",
    productName: "AZ 42mm Harmonic Planetary Gear",
    modelNumber: "AZM46MC-HP5",
    sampleModel: "AZM46MC-HP5",
    motorType: "클로즈드루프 스텝모터",
    phaseTypes: ["1상 AC", "3상 AC"],
    imageUrl: "https://catalog.orientalmotor.com/Asset/azm46ac-img.jpg",
    powerW: 120,
    maxMotorRpm: 4500,
    minMotorRpm: 0,
    gearheadType: "하모닉 유성감속기",
    availableRatios: [5],
    maxOutputTorqueNm: 1.5,
    verticalReady: true,
    notes: "작은 백래시와 높은 정밀도가 필요한 장비에 적합합니다.",
    sourceLabel: "AZ Harmonic official spec",
    sourceUrl: "https://catalog.orientalmotor.com/item/az-series-42mm-absolute-stepper-motors/az-series-42mm-absolute-encoder-stepper-motors-ac/azm46mc-hp5",
  },
];

const HYOSUNG_MOTOR_PRODUCTS = [
  {
    company: "Hyosung",
    series: "Low Voltage Motors IE3",
    productName: "효성 저압 3상 유도전동기 0.75kW 4P",
    modelNumber: "FR 80M-4P",
    sampleModel: "IE3 / 0.75kW / 4극 / 외장 감속기 조합형",
    motorType: "3상 유도전동기",
    phaseTypes: ["3상 AC"],
    imageUrl: null,
    powerW: 750,
    maxMotorRpm: 1800,
    minMotorRpm: 300,
    gearheadType: "외장 감속기 조합형",
    availableRatios: STANDARD_GEAR_RATIOS,
    ratedMotorTorqueNm: 4.0,
    verticalReady: false,
    externalReducerOnly: true,
    notes: "연속 회전에 적합한 일반 산업용 모터입니다. 컨베이어와 펌프, 이송 설비 쪽 검토에 맞습니다.",
    manualIds: ["hyosung-lv-motor", "hyosung-lvss", "hyosung-motorsol"],
    sourceLabel: "효성 저압 모터 카탈로그",
    sourceUrl: "/manuals/hyosung/hyosung-low-voltage-motors-catalog-kr.pdf",
  },
  {
    company: "Hyosung",
    series: "Low Voltage Motors IE3",
    productName: "효성 저압 3상 유도전동기 1.5kW 4P",
    modelNumber: "FR 90L-4P",
    sampleModel: "IE3 / 1.5kW / 4극 / 외장 감속기 조합형",
    motorType: "3상 유도전동기",
    phaseTypes: ["3상 AC"],
    imageUrl: null,
    powerW: 1500,
    maxMotorRpm: 1800,
    minMotorRpm: 300,
    gearheadType: "외장 감속기 조합형",
    availableRatios: STANDARD_GEAR_RATIOS,
    ratedMotorTorqueNm: 8.0,
    verticalReady: false,
    externalReducerOnly: true,
    notes: "중소형 산업 설비에서 많이 쓰는 기본형입니다. 감속기와 함께 조합해 이송 설비 검토에 활용합니다.",
    manualIds: ["hyosung-lv-motor", "hyosung-empr", "hyosung-lvss"],
    sourceLabel: "효성 저압 모터 카탈로그",
    sourceUrl: "/manuals/hyosung/hyosung-low-voltage-motors-catalog-kr.pdf",
  },
];

const NANOMOTION_MOTOR_PRODUCTS = [
  {
    company: "Nanomotion",
    series: "RC3 Ultrasonic Motor",
    productName: "RC3 Ultrasonic Linear Motor",
    sampleModel: "RC3 / max 180 mm/s / dynamic stall force 12 N",
    motorType: "초소형 정밀 모터",
    phaseTypes: ["1상 AC"],
    imageUrl: null,
    powerW: 17,
    maxMotorRpm: 0,
    minMotorRpm: 0,
    gearheadType: "직결 / 감속기 없음",
    availableRatios: [1],
    verticalReady: true,
    driveMode: "linear-direct",
    maxLinearSpeedMmS: 180,
    maxLinearForceN: 12,
    staticHoldingForceN: 12,
    notes: "RC3는 스크류 없이 직결 정밀 스테이지에 많이 쓰는 초음파 모터입니다.",
    manualIds: ["nanomotion-rc3"],
    sourceLabel: "RC3 user manual",
    sourceUrl: "/manuals/nanomotion/nanomotion-rc3-ultrasonic-motor-user-manual.pdf",
  },
  {
    company: "Nanomotion",
    series: "HR Motors",
    productName: "HR8 Direct Drive Motor",
    sampleModel: "HR8 / max 250 mm/s / dynamic stall force 36 N",
    motorType: "초소형 정밀 모터",
    phaseTypes: ["1상 AC"],
    imageUrl: null,
    powerW: 40,
    maxMotorRpm: 0,
    minMotorRpm: 0,
    gearheadType: "직결 / 감속기 없음",
    availableRatios: [1],
    verticalReady: true,
    driveMode: "linear-direct",
    maxLinearSpeedMmS: 250,
    maxLinearForceN: 36,
    staticHoldingForceN: 28,
    notes: "HR 계열 중 가장 높은 추력이 필요한 정밀 장비용 직결 모터입니다.",
    manualIds: ["nanomotion-hr"],
    sourceLabel: "HR motors user manual",
    sourceUrl: "/manuals/nanomotion/nanomotion-hr-motors-user-manual.pdf",
  },
];

const YASKAWA_MOTOR_PRODUCTS = [
  {
    company: "Yaskawa",
    series: "Sigma-7 S7J Gear Motors",
    productName: "S7J 100W Servo Gear Motor",
    modelNumber: "S7J01A-VL050-05 / SGM7J-01A7D61",
    sampleModel: "S7J 100W / 5:1 / Sigma-7",
    motorType: "브러시리스 모터",
    phaseTypes: ["3상 AC"],
    imageUrl: null,
    powerW: 100,
    maxMotorRpm: 3000,
    minMotorRpm: 0,
    gearheadType: "유성 감속기 조합형",
    availableRatios: [3, 5, 10, 25, 50],
    ratedMotorTorqueNm: 0.318,
    verticalReady: true,
    notes: "Sigma-7 100W 기반 기어드 서보 조합입니다.",
    sourceLabel: "Yaskawa S7J gear motors",
    sourceUrl: "https://www.yaskawa.com/products/motion/sigma-7-servo-products/gear-motors/s7j-gear-motors/-/content/_2c53e706-8c7e-4440-840b-49ab8ed23732_Models38Ratings",
  },
];

const MITSUBISHI_MOTOR_PRODUCTS = [
  {
    company: "Mitsubishi Electric",
    series: "MELSERVO-JE HG-KN",
    productName: "HG-KN13J Servo Motor",
    modelNumber: "HG-KN13J",
    sampleModel: "HG-KN13J / 100W / 3000 rpm",
    motorType: "브러시리스 모터",
    phaseTypes: ["3상 AC"],
    imageUrl: null,
    powerW: 100,
    maxMotorRpm: 3000,
    minMotorRpm: 0,
    gearheadType: "외장 감속기 조합형",
    availableRatios: STANDARD_GEAR_RATIOS,
    ratedMotorTorqueNm: 0.32,
    verticalReady: true,
    externalReducerOnly: true,
    notes: "MR-JE 계열 전용의 소형 서보 모터입니다.",
    sourceLabel: "Mitsubishi HG-KN specification",
    sourceUrl: "https://us.mitsubishielectric.com/fa/en/products/drive-products/ac-servos-melservo/mrje/motor/specifications/",
  },
];

const SIEMENS_MOTOR_PRODUCTS = [
  {
    company: "Siemens",
    series: "SIMOTICS S-1FK2",
    productName: "1FK2102 HD Servo Motor",
    modelNumber: "1FK2102-0AG00-0MA0",
    sampleModel: "1FK2102 / 0.05kW / 3000 rpm",
    motorType: "브러시리스 모터",
    phaseTypes: ["1상 AC", "3상 AC"],
    imageUrl: null,
    powerW: 50,
    maxMotorRpm: 3000,
    minMotorRpm: 0,
    gearheadType: "외장 감속기 조합형",
    availableRatios: STANDARD_GEAR_RATIOS,
    ratedMotorTorqueNm: 0.16,
    verticalReady: true,
    externalReducerOnly: true,
    notes: "공간이 좁은 장비에 자주 검토하는 1FK2 서보입니다.",
    sourceLabel: "Siemens 1FK2 product detail",
    sourceUrl: "https://mall.industry.siemens.com/mall/en/oms/Catalog/Product/1FK2102-0AG00-0MA0",
  },
];

const SEW_MOTOR_PRODUCTS = [
  {
    company: "SEW-EURODRIVE",
    series: "CMP Servo Motors",
    productName: "CMP40S Servo Motor",
    modelNumber: "CMP40S",
    sampleModel: "CMP40S / 3000 rpm / 0.5 Nm",
    motorType: "브러시리스 모터",
    phaseTypes: ["3상 AC"],
    imageUrl: null,
    powerW: 157,
    maxMotorRpm: 3000,
    minMotorRpm: 0,
    gearheadType: "외장 감속기 조합형",
    availableRatios: STANDARD_GEAR_RATIOS,
    ratedMotorTorqueNm: 0.5,
    verticalReady: true,
    externalReducerOnly: true,
    notes: "SEW 감속기와 조합한 이송축 검토에 적합한 서보 모터입니다.",
    sourceLabel: "SEW CMP motors",
    sourceUrl: "https://download.sew-eurodrive.com/download/html/30588332/en-EN/42305016843.html",
  },
];

const THK_MOTOR_PRODUCTS = [
  {
    company: "THK",
    series: "KR Series",
    productName: "KR20 Electric Actuator (100W Servo)",
    modelNumber: "KR20 / 100W",
    sampleModel: "KR20 + 100W 서보 / 볼스크류 pitch 5mm",
    motorType: "브러시리스 모터",
    phaseTypes: ["3상 AC"],
    imageUrl: null,
    powerW: 100,
    maxMotorRpm: 0,
    minMotorRpm: 0,
    gearheadType: "직결 / 감속기 없음",
    availableRatios: [1],
    verticalReady: true,
    driveMode: "linear-direct",
    maxLinearSpeedMmS: 500,
    maxLinearForceN: 160,
    staticHoldingForceN: 130,
    notes: "볼스크류·LM가이드 내장 소형 일체형 액추에이터. 반도체·소형 정밀 장비에 많이 씁니다.",
    manualIds: ["thk-kr-actuator"],
    sourceLabel: "THK KR Series 공식 카탈로그",
    sourceUrl: "https://www.thk.com/jp/en/products/categories/electric_actuator/kr.html",
  },
  {
    company: "THK",
    series: "KR Series",
    productName: "KR26 Electric Actuator (200W Servo)",
    modelNumber: "KR26 / 200W",
    sampleModel: "KR26 + 200W 서보 / 볼스크류 pitch 10mm",
    motorType: "브러시리스 모터",
    phaseTypes: ["3상 AC"],
    imageUrl: null,
    powerW: 200,
    maxMotorRpm: 0,
    minMotorRpm: 0,
    gearheadType: "직결 / 감속기 없음",
    availableRatios: [1],
    verticalReady: true,
    driveMode: "linear-direct",
    maxLinearSpeedMmS: 500,
    maxLinearForceN: 380,
    staticHoldingForceN: 300,
    notes: "중하중 정밀 이송에 많이 쓰는 표준형 일체형 액추에이터. 구동계 설계 공수가 줄어드는 장점이 있습니다.",
    manualIds: ["thk-kr-actuator"],
    sourceLabel: "THK KR Series 공식 카탈로그",
    sourceUrl: "https://www.thk.com/jp/en/products/categories/electric_actuator/kr.html",
  },
  {
    company: "THK",
    series: "KR Series",
    productName: "KR33 Electric Actuator (400W Servo)",
    modelNumber: "KR33 / 400W",
    sampleModel: "KR33 + 400W 서보 / 볼스크류 pitch 10mm",
    motorType: "브러시리스 모터",
    phaseTypes: ["3상 AC"],
    imageUrl: null,
    powerW: 400,
    maxMotorRpm: 0,
    minMotorRpm: 0,
    gearheadType: "직결 / 감속기 없음",
    availableRatios: [1],
    verticalReady: true,
    driveMode: "linear-direct",
    maxLinearSpeedMmS: 500,
    maxLinearForceN: 700,
    staticHoldingForceN: 560,
    notes: "디스플레이·반도체 장비의 주축 이송에 검토하는 고추력 일체형 액추에이터입니다.",
    manualIds: ["thk-kr-actuator"],
    sourceLabel: "THK KR Series 공식 카탈로그",
    sourceUrl: "https://www.thk.com/jp/en/products/categories/electric_actuator/kr.html",
  },
  {
    company: "THK",
    series: "KR Series",
    productName: "KR46 Electric Actuator (750W Servo)",
    modelNumber: "KR46 / 750W",
    sampleModel: "KR46 + 750W 서보 / 볼스크류 pitch 20mm",
    motorType: "브러시리스 모터",
    phaseTypes: ["3상 AC"],
    imageUrl: null,
    powerW: 750,
    maxMotorRpm: 0,
    minMotorRpm: 0,
    gearheadType: "직결 / 감속기 없음",
    availableRatios: [1],
    verticalReady: true,
    driveMode: "linear-direct",
    maxLinearSpeedMmS: 500,
    maxLinearForceN: 1300,
    staticHoldingForceN: 1000,
    notes: "대형 고하중 장비용 볼스크류 내장 일체형 액추에이터입니다. 별도 LM가이드 설계가 필요 없어 조립 공수가 줄어듭니다.",
    manualIds: ["thk-kr-actuator"],
    sourceLabel: "THK KR Series 공식 카탈로그",
    sourceUrl: "https://www.thk.com/jp/en/products/categories/electric_actuator/kr.html",
  },
  {
    company: "THK",
    series: "SKR Series",
    productName: "SKR46V Electric Actuator (200W Servo)",
    modelNumber: "SKR46V / 200W",
    sampleModel: "SKR46V + 200W 서보 / 볼스크류 pitch 10mm",
    motorType: "브러시리스 모터",
    phaseTypes: ["3상 AC"],
    imageUrl: null,
    powerW: 200,
    maxMotorRpm: 0,
    minMotorRpm: 0,
    gearheadType: "직결 / 감속기 없음",
    availableRatios: [1],
    verticalReady: true,
    driveMode: "linear-direct",
    maxLinearSpeedMmS: 600,
    maxLinearForceN: 480,
    staticHoldingForceN: 380,
    notes: "폭이 좁은 슬림 설계가 필요한 장비에 적합합니다. KR 대비 설치 폭이 작아 공간 제약 장비에 유리합니다.",
    manualIds: ["thk-skr-actuator"],
    sourceLabel: "THK SKR Series 공식 카탈로그",
    sourceUrl: "https://www.thk.com/jp/en/products/categories/electric_actuator/skr.html",
  },
  {
    company: "THK",
    series: "SKR Series",
    productName: "SKR55V Electric Actuator (400W Servo)",
    modelNumber: "SKR55V / 400W",
    sampleModel: "SKR55V + 400W 서보 / 볼스크류 pitch 20mm",
    motorType: "브러시리스 모터",
    phaseTypes: ["3상 AC"],
    imageUrl: null,
    powerW: 400,
    maxMotorRpm: 0,
    minMotorRpm: 0,
    gearheadType: "직결 / 감속기 없음",
    availableRatios: [1],
    verticalReady: true,
    driveMode: "linear-direct",
    maxLinearSpeedMmS: 600,
    maxLinearForceN: 900,
    staticHoldingForceN: 720,
    notes: "중대형 장비의 슬림 이송축에 적합한 고추력 슬림형 일체형 액추에이터입니다.",
    manualIds: ["thk-skr-actuator"],
    sourceLabel: "THK SKR Series 공식 카탈로그",
    sourceUrl: "https://www.thk.com/jp/en/products/categories/electric_actuator/skr.html",
  },
];

const NANOTEC_MOTOR_PRODUCTS = [
  {
    company: "Nanotec",
    series: "LGA42 Linear Actuator",
    productName: "LGA42 Captive Linear Actuator",
    modelNumber: "LGA421S14-B-UIBF-038",
    sampleModel: "LGA42 / 20 mm/s / 551 N",
    motorType: "2상 스텝모터",
    phaseTypes: ["2상"],
    imageUrl: null,
    powerW: 20,
    maxMotorRpm: 0,
    minMotorRpm: 0,
    gearheadType: "직결 / 감속기 없음",
    availableRatios: [1],
    verticalReady: true,
    driveMode: "linear-direct",
    maxLinearSpeedMmS: 20,
    maxLinearForceN: 551,
    staticHoldingForceN: 551,
    notes: "Nanotec 캡티브 리니어 액추에이터입니다.",
    sourceLabel: "Nanotec LGA42 product",
    sourceUrl: "https://www.nanotec.com/eu/en/products/87095848-",
  },
];

export const PRODUCT_CATALOG = [
  ...ORIENTAL_MOTOR_PRODUCTS,
  ...THK_MOTOR_PRODUCTS,
  ...NANOMOTION_MOTOR_PRODUCTS,
  ...HYOSUNG_MOTOR_PRODUCTS,
  ...YASKAWA_MOTOR_PRODUCTS,
  ...MITSUBISHI_MOTOR_PRODUCTS,
  ...SIEMENS_MOTOR_PRODUCTS,
  ...SEW_MOTOR_PRODUCTS,
  ...NANOTEC_MOTOR_PRODUCTS,
];
